export enum ServiceOptionsEnum {
  AllServices = "",
  MaintenanceDiagnostics = "maintenance_diagnostics",
  TransmissionRepair = "transmission_repair",
  EngineRepair = "engine_repair",
  SuspensionRepair = "suspension_repair",
  AutoElectrical = "auto_electrical",
  ACRepair = "ac_repair",
  TireService = "tire_service",
  WheelAlignment = "wheel_alignment",
  BodyRepair = "body_repair",
  DetailingPolishing = "detailing_polishing",
  PaintingServices = "painting_services",
  ChipTuning = "chip_tuning",
  AutomotiveMachining = "automotive_machining",
  EVRepair = "ev_repair",
}

export enum WorkPricingOptionsEnum {
  FixedPricing = "fixed_pricing",
  StartingFrom = "starting_from",
  AfterInspection = "after_inspection",
}

export enum CarMakeEnum {
  Any = "",
  Acura = "acura",
  AlfaRomeo = "alfa_romeo",
  Audi = "audi",
  BMW = "bmw",
  Buick = "buick",
  Cadillac = "cadillac",
  Chevrolet = "chevrolet",
  Chrysler = "chrysler",
  Citroen = "citroen",
  Dodge = "dodge",
  Ferrari = "ferrari",
  Fiat = "fiat",
  Ford = "ford",
  Genesis = "genesis",
  GMC = "gmc",
  Honda = "honda",
  Hyundai = "hyundai",
  Infiniti = "infiniti",
  Jaguar = "jaguar",
  Jeep = "jeep",
  Kia = "kia",
  Lamborghini = "lamborghini",
  LandRover = "land_rover",
  Lexus = "lexus",
  Lincoln = "lincoln",
  Maserati = "maserati",
  Mazda = "mazda",
  MercedesBenz = "mercedes_benz",
  Mini = "mini",
  Mitsubishi = "mitsubishi",
  Nissan = "nissan",
  Opel = "opel",
  Peugeot = "peugeot",
  Pontiac = "pontiac",
  Porsche = "porsche",
  Ram = "ram",
  Renault = "renault",
  RollsRoyce = "rolls_royce",
  Skoda = "skoda",
  Subaru = "subaru",
  Suzuki = "suzuki",
  Tesla = "tesla",
  Toyota = "toyota",
  Volkswagen = "volkswagen",
  Volvo = "volvo",
}

// export enum EstimatedTimeOptionsEnum {
//   SameDay = "same_day",
//   OneToTwoDays = "one_to_two_days",
//   ThreeToFiveDays = "three_to_five_days",
//   OneWeek = "one_week",
//   TwoWeeks = "two_weeks",
//   OneMonthPlus = "one_month_plus",
// }

// export enum PriceFromOptionsEnum {
//   UpTo50 = "UP_TO_50",
//   UpTo100 = "UP_TO_100",
//   UpTo300 = "UP_TO_300",
//   UpTo500 = "UP_TO_500",
//   Above500 = "ABOVE_500",
// }
