export const STO = {
  id: "sto_12345678-90ab-cdef-ghij-klmnopqrstuv",
  name: "AutoPro Львів - Кузов та Діагностика",
  slug: "autopro-lviv-kuzov-diagnostyka",
  description:
    "Сучасний автосервіс у Львові з 2018 року. Спеціалізуємось на кузовному ремонті, комп'ютерній діагностиці, ТО будь-яких марок, фарбуванні та відновленні геометрії кузова. Оригінальні та якісні аналогові запчастини. Гарантія до 2 років на роботи.",
  address: {
    city: "Львів",
    district: "Франківський",
    street: "Зелена",
    house: "45",
  },
  phones: ["+380672345678", "+380632345678"],
  email: "info@autopro.lviv.ua",
  website: "https://autopro.lviv.ua",
  social: {
    instagram: "https://instagram.com/autopro_lviv",
    facebook: "https://facebook.com/autopro.lviv",
    telegram: "https://t.me/autopro_lviv",
  },
  workingHours: {
    monday: "09:00 - 19:00",
    tuesday: "09:00 - 19:00",
    wednesday: "09:00 - 19:00",
    thursday: "09:00 - 19:00",
    friday: "09:00 - 19:00",
    saturday: "10:00 - 16:00",
    sunday: "вихідний",
  },
  services: [
    {
      id: "service_1",
      name: "Комп'ютерна діагностика",
      priceFrom: 450,
      priceTo: 1200,
      durationMinutes: 30,
      description:
        "Сканування всіх блоків, читання/скидання помилок, перевірка датчиків",
    },
    {
      id: "service_2",
      name: "Заміна ГРМ (з роликами)",
      priceFrom: 4500,
      priceTo: 9500,
      durationMinutes: 240,
      description: "Комплект ГРМ + робота. Ціна залежить від моделі авто",
    },
    {
      id: "service_3",
      name: "Кузовний ремонт (пошкодження до 30 см)",
      priceFrom: 3500,
      priceTo: 18000,
      durationMinutes: 480,
      description: "Вирівнювання, шпатлювання, фарбування",
    },
    {
      id: "service_4",
      name: "Шиномонтаж (R17-R22)",
      priceFrom: 600,
      priceTo: 1200,
      durationMinutes: 45,
      description: "Переобування + балансування 4 коліс",
    },
  ],
  brands: [
    "Volkswagen",
    "Toyota",
    "BMW",
    "Mercedes",
    "Skoda",
    "Audi",
    "Honda",
    "Ford",
    "Renault",
  ],
  certificates: [
    {
      name: "Офіційний партнер Bosch Service",
      imageUrl: "https://example.com/cert/bosch.jpg",
      issuedAt: "2023-05-15",
    },
    {
      name: "Сертифікат 3M для кузовного ремонту",
      imageUrl: "https://example.com/cert/3m.jpg",
      issuedAt: "2024-02-10",
    },
  ],
  photos: [
    {
      id: "photo_1",
      url: "https://example.com/sto/autopro-reception.jpg",
      alt: "Рецепція та зона очікування",
      isMain: true,
    },
    {
      id: "photo_2",
      url: "https://example.com/sto/autopro-boxes.jpg",
      alt: "Робочі бокси з підйомниками",
      isMain: false,
    },
    {
      id: "photo_3",
      url: "https://example.com/sto/autopro-paint.jpg",
      alt: "Камера фарбування",
      isMain: false,
    },
    {
      id: "photo_4",
      url: "https://example.com/sto/autopro-before-after.jpg",
      alt: "Приклад кузовного ремонту до/після",
      isMain: false,
    },
  ],
  reviews: [
    {
      id: "review_1",
      author: "Олег К.",
      rating: 5,
      text: "Швидко і якісно зробили діагностику та заміну ГРМ на Skoda Octavia. Рекомендую!",
      createdAt: "2025-12-15T14:30:00Z",
      carModel: "Skoda Octavia 2020",
    },
    {
      id: "review_2",
      author: "Марія П.",
      rating: 4,
      text: "Після ДТП відновили бампер і двері. Колір ідеально підібрали. Трохи довго чекала, але результат супер.",
      createdAt: "2026-01-20T09:45:00Z",
      carModel: "Toyota RAV4 2022",
    },
    {
      id: "review_3",
      author: "Андрій М.",
      rating: 5,
      text: "Найкращий кузовний у Львові за співвідношенням ціна/якість. Роблять швидко і дають гарантію.",
      createdAt: "2026-02-10T18:15:00Z",
      carModel: "BMW X5 2019",
    },
  ],
  averageRating: 4.7,
  reviewCount: 128,
  isVerified: true,
  isPartner: true,
  createdAt: "2018-06-01T00:00:00Z",
  updatedAt: "2026-02-20T14:22:00Z",
};
